//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Relation.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelationShipType
    {
        public RelationShipType()
        {
            this.Relationships = new HashSet<Relationship>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Relationship> Relationships { get; set; }
    }
}
